language: php

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--prefer-dist --no-interaction --no-progress --optimize-autoloader"
    - TASK_STATIC_ANALYSIS=0
    - TASK_TESTS_COVERAGE=0

matrix:
  include:
    - php: "7.4"
      env:
        - TASK_STATIC_ANALYSIS=0 # set to 1 to enable static analysis
        - TASK_TESTS_COVERAGE=1

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug is not installed"

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install $DEFAULT_COMPOSER_FLAGS
  - |
    if [ $TASK_STATIC_ANALYSIS == 1 ]; then
      pecl install ast
    fi

before_script:
  - php --version
  - composer --version
  # enable code coverage
  - |
    if [ $TASK_TESTS_COVERAGE == 1 ]; then
        PHPUNIT_COVERAGE_FLAG="--coverage-clover=coverage.clover"
    fi

script:
  - phpdbg -qrr vendor/bin/phpunit --verbose $PHPUNIT_COVERAGE_FLAG
  - |
    if [ $TASK_STATIC_ANALYSIS == 1 ]; then
      composer phan
    fi
  - |
    if [ $TASK_STATIC_ANALYSIS == 1 ]; then
      cat analysis.txt
    fi

after_script:
  - |
    if [ $TASK_TESTS_COVERAGE == 1 ]; then
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi


notifications:
  slack:
    -
      rooms:
        -
          secure: q+9VDUJqfhU3pQiY+iq6iu9iCtpHDvd0hXb3mXbTT571doQSaPV8UOKeu2t/Vj0nW9uUHxYtj3M2Dl6NwpLfdWLETjjrCM0STCEhWhWXeeW+mCy3aREdbptPJz8VA0C45Crn+/hMQgm67CPoXQdtbtn0URs1KZJpTTHrgfJOJn6MvMX9/rMhxoPq5Jav8aXwHRO3/Llfc84Wi+Ukew0GPKsCP1uiIztlKrJEW5v9SgvP9UxS1EYan16ebMuK3vebgpjDgRBURfEJ+j/fAVaSIDdPQ/Nsk2SJpfmk0rZEPeAqH3IRAOin6Omabp90FxVV9deeW8j6XBEAH6pSvHJxTbnrFSzpu5q2UwKXrDNLSmINdpvgufBaKhSdHpFGb0jFEsqw1iFPJpkFlj9mn/hEKvQxmgR3poLjFL7oGmihQwzsGSnPydGnz+l5tvTU7c8HDg3HKVlsvTLFMqqukdIeiGQLB59Uour6EW32X5LR1couvfxUPaxAC8MC/zQgWGFgjqCt9RjMWAIdjqLOcH9Dl1GeAuS2itRrK1qQ2QV8Ek3a1GpszT1KfeAhVnBjHexBS63En96nePmIglCaKNu9BaAcsXo+m2gb3LkgYIGvEIZ66vMUN1sDDZ7whToFl9ItfO7jv0nXuaFMkGW5m+8ZBgedK3yHFOAqtoSsVpQuz40=
      on_success: always
      on_failure: never
      on_pull_requests: false
    -
      rooms:
        -
          secure: Wo4hbq3OnC1EV59vjFxvbadEyPDqN8lh6uHVu0l85EQoMOXtgwA4fvvcX3u27L51TSMvKuACggJErA06rjzHhsWcA50rQgeTklJyK32SOa/CmA5Yd9vwT+7GBNXkhbgYj5D3KemjHV8nGlARSM6GZpPvVPJ4EAKdLHqGO1iQqUdtaRELQ1pXKYfAUxjLQkvTuk6O33RxWyzemPJk0qSJp8MnTJMExTsXH15MQDmXp0aNmb3cwUoJmll869f2ffZ3T46Engob5F1EUx076+yGSxNUzttsSvSYWPrv16DWeHyujuai4mCL3bqDdYNYFpFQEH8yvhflHZ9FRkPjFzxYNaY9hQfwOFTIfEr1WwUuH8lGvcFc30+9p4fuWD9oLsV9xJU/SQ1acWhxkna6WOr7i1uvCotrtgz7kXsHKryBIRo+1dN0UzbWV6ZYD2KBhxzPjiOLGUoiCko85wrlxPuj4ycisPknbfyx38DDoqGMwqk7HBzX2aWo0vFGoY2toHgn66EVV0ajfc043El1cmkY4l85vXi2B43OFzjiTA5V+hV/ijzUe9zlDD+mdMzT0OOVpk/xNC07cg/I5B1nFMGlS9GFkgLw9GXBjxMo4LVLr+Z5bRzTqHpgaYGXoahaZqi2j41gn07zJd02MP6NJpj9l/RxR+mkHdF5I1t4w01TIc0=
      on_success: never
      on_failure: always
      on_pull_requests: false
